# Generated by Django 4.2.5 on 2023-10-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name_plural': '10.Seller'},
        ),
        migrations.AddField(
            model_name='seller',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seller')),
            ],
            options={
                'verbose_name_plural': '11.SellerReview',
            },
        ),
    ]
