# Generated by Django 4.2.5 on 2023-10-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_seller_options_seller_is_suspended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name_plural': '10. Seller'},
        ),
    ]
