# Generated by Django 4.2.5 on 2023-10-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_seller_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_suspended',
        ),
        migrations.AddField(
            model_name='seller',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SellerReview',
        ),
    ]
