# Generated by Django 4.2.5 on 2023-10-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_stkpushrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stkpushrequest',
            old_name='total_amount',
            new_name='total_amt',
        ),
    ]
