# Generated by Django 4.2.5 on 2023-10-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_total_amount_stkpushrequest_total_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stkpushrequest',
            name='created_at',
        ),
    ]
